name: Keep Alive Workflow

on:
  schedule:
    - cron: '0 0 1 */1 *'  # Run at midnight on the 1st day of every month (change to every 30 days as needed)
  workflow_dispatch:       # Allow manual triggering

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update keepalive file
        run: |
          date >> keepalive.log

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add keepalive.log
          git commit -m "chore: keep alive" || echo "No changes to commit"
          git push origin HEAD
