name: Keep Alive Workflow

on:
  schedule:
    - cron: '0 0 1 */1 *'  # Corre el día 1 de cada mes a las 00:00 UTC
  workflow_dispatch:       # Permite ejecutarlo manualmente desde GitHub

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update keepalive file
        run: |
          date >> keepalive.log

      - name: Commit and push if changed
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "Santiago Olivos"
          git config user.email "santiagoolivos@users.noreply.github.com"
          git add keepalive.log
          git commit -m "chore: keep alive" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:main
